spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/db4
    username: postgres
    password: 112233qq
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    baseline-on-migrate: true


